spring.application.name=banking-app

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=bankuser
spring.datasource.password=bankpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always